pip install batchgenerators
pip install einops
pip install matplotlib
pip install ml_collections
pip install monai
pip install nibabel
pip install nni
pip install numpy
pip install opencv_python
pip install Pillow
pip install pydensecrf
pip install scipy
pip install SimpleITK
pip install scikit-image
pip install Surface_Distance_Based_Measures
pip install tifffile
pip install timm
pip install torch
pip install torchtoolbox
pip install torchvision
pip install tqdm
pip install torchmetrics
pip install tensorboard
pip install pyyaml