CUDA_VISIBLE_DEVICES: '0'
T_0: 2
T_max: 2
T_mult: 2
augmentation_method: Choice
augmentation_probability: 0.3
batch_size: 1
benchmark: false
best_dice: 0.6
class_weight:
- 0.00551122
- 0.99448878
classes: 2
clip_lower_bound: -1412
clip_upper_bound: 17943
create_data: false
crop_size: !!python/tuple
- 160
- 160
- 96
crop_stride:
- 32
- 32
- 32
crop_threshold: 0.5
cuda: true
dataset_name: 3D-CBCT-Tooth
dataset_path: ./datasets/3D-CBCT-Tooth
deterministic: true
dice_loss_mode: extension
dice_mode: standard
elastic_transform_alpha: 1
elastic_transform_sigma: 20
end_epoch: 20
factor: 0.5
gamma: 0.1
gaussian_noise_mean: 0
gaussian_noise_std: 0.01
in_channels: 1
index_to_class_dict:
  0: background
  1: foreground
learning_rate: 0.0005
loss_function_name: DiceLoss
lr_scheduler_name: ReduceLROnPlateau
metric_names:
- DSC
milestones:
- 1
- 3
- 5
- 7
- 8
- 9
mode: max
model_name: PMFSNet
momentum: 0.8
normalize_mean: 0.05029342141696459
normalize_std: 0.028477091559295814
num_workers: 2
open_elastic_transform: true
open_gaussian_noise: true
open_random_flip: true
open_random_rescale: true
open_random_rotate: true
open_random_shift: true
optimize_params: false
optimizer_name: Adam
patience: 1
pretrain: null
random_rescale_max_percentage: 1.5
random_rescale_min_percentage: 0.5
random_rotate_max_angle: 50
random_rotate_min_angle: -50
random_shift_max_percentage: 0.3
resample_spacing:
- 0.5
- 0.5
- 0.5
resume: null
run_dir: ./runs
samples_train: 2048
save_epoch_freq: 4
seed: 1777777
sigmoid_normalization: false
start_epoch: 0
step_size: 9
terminal_show_freq: 256
update_weight_freq: 32
use_amp: false
weight_decay: 5.0e-05
